"""
REPLAY BUFFER FOR REINFORCEMENT LEARNING
Required for Self-Play Training

This module provides a replay buffer for storing and sampling
self-play training examples during reinforcement learning.
"""

import os
import random
from collections import deque
from typing import Dict, List, Optional, Sequence, Union
from dataclasses import dataclass

import numpy as np
import chess
import torch
import pickle


@dataclass
class GameExample:
    """
    Training example from self-play (memory-efficient format).

    This is the format generated by self_play module.
    """

    fen: str
    policy: Dict[str, float]  # UCI string -> probability
    value: float
    move_number: int


class ReplayBuffer:
    """
    Replay buffer for storing self-play training examples.

    Stores positions from self-play games and provides sampling
    for training the neural network.

    Features:
    - Memory-efficient storage (FEN strings)
    - Fixed maximum size (FIFO when full)
    - Random sampling for training
    - Move history tracking for RNN
    """

    def __init__(self, max_size: int = 100000, memory_efficient: bool = True):
        """
        Initialize replay buffer.

        Args:
            max_size: Maximum number of examples to store
            memory_efficient: If True, store FEN strings instead of Board objects
                             (saves memory but adds conversion overhead)
        """
        self.max_size = max_size
        self.memory_efficient = memory_efficient
        self.buffer: deque = deque(maxlen=max_size)

    def add(
        self,
        board: chess.Board,
        policy_target: Union[torch.Tensor, Dict[str, float]],
        value_target: float,
        move_history: Optional[Sequence[chess.Move]] = None,
    ) -> None:
        """
        Add a training example to the buffer.

        Args:
            board: Chess board position
            policy_target: Target policy distribution (visit counts from MCTS)
            value_target: Target value (game outcome: 1.0, 0.0, -1.0)
            move_history: Optional move history for RNN
        """
        if self.memory_efficient:
            # Store FEN string instead of Board object
            example = {
                "fen": board.fen(),
                "policy": policy_target,
                "value": value_target,
                "move_history": (
                    [move.uci() for move in move_history] if move_history else []
                ),
            }
        else:
            example = {
                "board": board.copy(),
                "policy": policy_target,
                "value": value_target,
                "move_history": list(move_history) if move_history else [],
            }
        self.buffer.append(example)

    def add_game(
        self,
        positions: Sequence[chess.Board],
        policies: Sequence[Union[torch.Tensor, Dict[str, float]]],
        outcome: float,
        move_histories: Optional[Sequence[Sequence[chess.Move]]] = None,
    ) -> None:
        """
        Add all positions from a complete game.

        Args:
            positions: List of board positions from the game
            policies: List of policy targets (one per position)
            outcome: Game outcome from perspective of first player
                    (1.0 = white win, 0.0 = draw, -1.0 = black win)
            move_histories: Optional move histories for each position
        """
        if move_histories is None:
            move_histories = [[] for _ in positions]

        for i, (board, policy, history) in enumerate(
            zip(positions, policies, move_histories)
        ):
            # Flip value based on whose turn it is
            value = outcome if board.turn == chess.WHITE else -outcome

            self.add(board, policy, value, history)

    def add_game_example(self, example: GameExample) -> None:
        """
        Add a single GameExample from self_play.

        Args:
            example: GameExample object from self_play module
        """
        # GameExample already stores FEN string
        internal_example = {
            "fen": example.fen,
            "policy": example.policy,
            "value": example.value,
            "move_history": [],  # GameExample doesn't track move history
            "move_number": example.move_number,
        }
        self.buffer.append(internal_example)

    def add_game_examples(self, examples: List[GameExample]) -> None:
        """
        Bulk add GameExample objects from self_play.

        Args:
            examples: List of GameExample objects
        """
        for example in examples:
            self.add_game_example(example)

    def sample(self, batch_size: int) -> Dict[str, List]:
        """
        Sample a random batch of examples.

        Args:
            batch_size: Number of examples to sample

        Returns:
            Dictionary with keys:
            - 'boards': List of chess.Board objects
            - 'policies': List of policy targets
            - 'values': List of value targets
            - 'move_histories': List of move history lists
        """
        if len(self.buffer) < batch_size:
            batch_size = len(self.buffer)

        batch = random.sample(self.buffer, batch_size)

        if self.memory_efficient:
            # Convert FEN strings back to Board objects
            return {
                "boards": [chess.Board(example["fen"]) for example in batch],
                "policies": [example["policy"] for example in batch],
                "values": [example["value"] for example in batch],
                "move_histories": [
                    [chess.Move.from_uci(m) for m in example["move_history"]]
                    for example in batch
                ],
            }
        else:
            return {
                "boards": [example["board"] for example in batch],
                "policies": [example["policy"] for example in batch],
                "values": [example["value"] for example in batch],
                "move_histories": [example["move_history"] for example in batch],
            }

    def __len__(self) -> int:
        """Return current number of examples in buffer"""
        return len(self.buffer)

    def clear(self) -> None:
        """Clear all examples from buffer"""
        self.buffer.clear()

    def is_full(self) -> bool:
        """Check if buffer is at maximum capacity"""
        return len(self.buffer) >= self.max_size

    def save(self, filepath: str) -> None:
        """Save buffer to disk"""
        directory = os.path.dirname(filepath)
        if directory:
            os.makedirs(directory, exist_ok=True)

        with open(filepath, "wb") as f:
            pickle.dump(
                {
                    "buffer": list(self.buffer),
                    "memory_efficient": self.memory_efficient,
                    "max_size": self.max_size,
                },
                f,
            )
        print(f"✅ Saved {len(self.buffer)} examples to {filepath}")

    def load(self, filepath: str) -> None:
        """Load buffer from disk"""
        with open(filepath, "rb") as f:
            data = pickle.load(f)

        if isinstance(data, dict) and "buffer" in data:
            self.buffer = deque(data["buffer"], maxlen=self.max_size)
            self.memory_efficient = data.get("memory_efficient", self.memory_efficient)
        else:
            self.buffer = deque(data, maxlen=self.max_size)

        print(f"✅ Loaded {len(self.buffer)} examples from {filepath}")

    def get_statistics(self) -> Dict[str, Union[int, float]]:
        """
        Get buffer statistics.

        Returns:
            Dictionary with statistics about buffer contents
        """
        if len(self.buffer) == 0:
            return {
                "size": 0,
                "capacity": self.max_size,
                "fill_percentage": 0.0,
                "avg_value": 0.0,
                "positive_ratio": 0.0,
            }

        values = [example["value"] for example in self.buffer]

        return {
            "size": len(self.buffer),
            "capacity": self.max_size,
            "fill_percentage": float(len(self.buffer) / self.max_size * 100),
            "avg_value": float(np.mean(values)),
            "value_std": float(np.std(values)),
            "positive_ratio": float(np.mean([value > 0 for value in values])),
            "negative_ratio": float(np.mean([value < 0 for value in values])),
            "draw_ratio": float(np.mean([value == 0 for value in values])),
        }


class PrioritizedReplayBuffer(ReplayBuffer):
    """
    Replay buffer with prioritized sampling.

    Samples examples based on their TD-error or other priority metric.
    Higher priority examples are sampled more frequently.

    This implements Prioritized Experience Replay (PER)
    """

    def __init__(
        self, max_size: int = 100000, alpha: float = 0.6, memory_efficient: bool = True
    ):
        """
        Initialize prioritized replay buffer.

        Args:
            max_size: Maximum number of examples to store
            alpha: Priority exponent (0 = uniform, 1 = fully prioritized)
            memory_efficient: Use memory-efficient storage
        """
        super().__init__(max_size, memory_efficient)
        self.alpha = alpha
        self.priorities: deque = deque(maxlen=max_size)

    def add(
        self,
        board: chess.Board,
        policy_target: Union[torch.Tensor, Dict[str, float]],
        value_target: float,
        move_history: Optional[Sequence[chess.Move]] = None,
        priority: float = 1.0,
    ) -> None:
        """
        Add example with priority.

        Args:
            board: Chess board position
            policy_target: Target policy distribution
            value_target: Target value
            move_history: Optional move history
            priority: Sample priority (default: 1.0 = max priority)
        """
        super().add(board, policy_target, value_target, move_history)
        self.priorities.append(priority)

    def add_game_example(self, example: GameExample, priority: float = 1.0) -> None:
        """Add GameExample with priority"""
        super().add_game_example(example)
        self.priorities.append(priority)

    def sample(self, batch_size: int, beta: float = 0.4) -> Dict[str, List]:
        """
        Sample batch using priorities.

        Args:
            batch_size: Number of examples to sample
            beta: Importance sampling exponent (0 = no correction, 1 = full)

        Returns:
            Dictionary with sampled examples and importance weights
        """
        if len(self.buffer) < batch_size:
            batch_size = len(self.buffer)

        # Compute sampling probabilities
        priorities = torch.tensor(list(self.priorities), dtype=torch.float32)
        probs = priorities**self.alpha
        probs /= probs.sum()

        # Sample indices
        indices = torch.multinomial(probs, batch_size, replacement=False)

        # Get examples
        batch = [self.buffer[i] for i in indices]

        # Compute importance sampling weights
        weights = (len(self.buffer) * probs[indices]) ** (-beta)
        weights /= weights.max()  # Normalize

        if self.memory_efficient:
            # Convert FEN strings back to Board objects
            result = {
                "boards": [chess.Board(example["fen"]) for example in batch],
                "policies": [example["policy"] for example in batch],
                "values": [example["value"] for example in batch],
                "move_histories": [
                    [chess.Move.from_uci(m) for m in example["move_history"]]
                    for example in batch
                ],
                "weights": weights.tolist(),
                "indices": indices.tolist(),
            }
        else:
            result = {
                "boards": [example["board"] for example in batch],
                "policies": [example["policy"] for example in batch],
                "values": [example["value"] for example in batch],
                "move_histories": [example["move_history"] for example in batch],
                "weights": weights.tolist(),
                "indices": indices.tolist(),
            }

        return result

    def update_priorities(self, indices: List[int], priorities: List[float]) -> None:
        """
        Update priorities for sampled examples.

        Typically called after computing TD-errors during training.

        Args:
            indices: Indices of examples to update
            priorities: New priority values (usually |TD-error| + epsilon)
        """
        for idx, priority in zip(indices, priorities):
            if 0 <= idx < len(self.priorities):
                self.priorities[idx] = priority

    def save(self, filepath: str) -> None:
        """Save prioritized buffer to disk"""
        directory = os.path.dirname(filepath)
        if directory:
            os.makedirs(directory, exist_ok=True)

        with open(filepath, "wb") as f:
            pickle.dump(
                {
                    "buffer": list(self.buffer),
                    "priorities": list(self.priorities),
                    "memory_efficient": self.memory_efficient,
                    "max_size": self.max_size,
                    "alpha": self.alpha,
                },
                f,
            )
        print(f"✅ Saved {len(self.buffer)} prioritized examples to {filepath}")

    def load(self, filepath: str) -> None:
        """Load prioritized buffer from disk"""
        with open(filepath, "rb") as f:
            data = pickle.load(f)

        self.buffer = deque(data["buffer"], maxlen=self.max_size)
        self.priorities = deque(
            data.get("priorities", [1.0] * len(self.buffer)), maxlen=self.max_size
        )
        self.memory_efficient = data.get("memory_efficient", self.memory_efficient)
        self.alpha = data.get("alpha", self.alpha)

        print(f"✅ Loaded {len(self.buffer)} prioritized examples from {filepath}")


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================


def convert_policy_dict_to_tensor(
    policy_dict: Dict[str, float],
    move_encoder,
    device: torch.device = torch.device("cpu"),
) -> torch.Tensor:
    """
    Convert policy dictionary to tensor format.

    Args:
        policy_dict: Dictionary mapping UCI strings to probabilities
        move_encoder: MoveEncoder instance
        device: Device to place tensor on

    Returns:
        Policy tensor with shape (4096,) or (1968,)
    """
    policy_tensor = torch.zeros(move_encoder.num_moves, device=device)

    for move_uci, prob in policy_dict.items():
        try:
            move = chess.Move.from_uci(move_uci)
            move_idx = move_encoder.encode_move(move)
            policy_tensor[move_idx] = prob
        except (ValueError, KeyError):
            # Invalid move or not in encoding
            continue

    return policy_tensor


def convert_policy_tensor_to_dict(
    policy_tensor: torch.Tensor, legal_moves: List[chess.Move], move_encoder
) -> Dict[str, float]:
    """
    Convert policy tensor to dictionary format.

    Args:
        policy_tensor: Policy tensor
        legal_moves: List of legal moves in position
        move_encoder: MoveEncoder instance

    Returns:
        Dictionary mapping UCI strings to probabilities
    """
    policy_dict = {}

    for move in legal_moves:
        try:
            move_idx = move_encoder.encode_move(move)
            prob = float(policy_tensor[move_idx])
            policy_dict[move.uci()] = prob
        except (KeyError, IndexError):
            # Move not in encoding
            continue

    return policy_dict
