"""
REPLAY BUFFER - Data Types & Storage

Provides data types and conversion utilities for replay buffer storage.
"""

from dataclasses import dataclass
from typing import Dict, List

import chess
import torch


@dataclass
class GameExample:
    """
    Training example from self-play (memory-efficient format).

    This is the format generated by the self_play module.
    """

    fen: str
    policy: Dict[str, float]  # UCI string -> probability
    value: float
    move_number: int


def convert_policy_dict_to_tensor(
    policy_dict: Dict[str, float],
    move_encoder,
    device: torch.device = torch.device("cpu"),
) -> torch.Tensor:
    """
    Convert policy dictionary to tensor format.

    Args:
        policy_dict: Dictionary mapping UCI strings to probabilities
        move_encoder: MoveEncoder instance
        device: Device to place tensor on

    Returns:
        Policy tensor with shape (4096,)
    """
    policy_tensor = torch.zeros(move_encoder.num_moves, device=device)

    for move_uci, prob in policy_dict.items():
        try:
            move = chess.Move.from_uci(move_uci)
            move_idx = move_encoder.encode_move(move)
            policy_tensor[move_idx] = prob
        except (ValueError, KeyError):
            continue

    return policy_tensor


def convert_policy_tensor_to_dict(
    policy_tensor: torch.Tensor, legal_moves: List[chess.Move], move_encoder
) -> Dict[str, float]:
    """
    Convert policy tensor to dictionary format.

    Args:
        policy_tensor: Policy tensor
        legal_moves: List of legal moves in position
        move_encoder: MoveEncoder instance

    Returns:
        Dictionary mapping UCI strings to probabilities
    """
    policy_dict = {}

    for move in legal_moves:
        try:
            move_idx = move_encoder.encode_move(move)
            prob = float(policy_tensor[move_idx])
            policy_dict[move.uci()] = prob
        except (KeyError, IndexError):
            continue

    return policy_dict
